# Site settings
title: Mauricio Urraco
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "Kashotex.net" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: The Public Enemies
user_description:Based in long island <a href="https://mauriciourraco.com" target="_blank">https://mauriciourraco.com</a>
user_title: Long Island
email: thepublicenemiesv1@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics


exclude: ['package.json', 'src' , 'node_modules']
